Repository ditrit/OGrEE-3D, pull requests merged in 2023-08, with the labels that each got.

#378 Add height of usableZone to groups & corridors
  Assets/Scripts/OgreeGenerators/ObjectGenerator.cs
Labels: bug

#385 Added distance in tiles to GetCoordinates
  Assets/Scripts/Inputs.cs
Labels: enhancement

#384 Wrong name of attribute
  Assets/Scripts/GUIObjectInfos.cs
  Assets/Scripts/OgreeClasses/Room.cs
Labels: bug

#389 386 objects color attribute is not taken into account when drawing it
  Assets/Scripts/Network/CliParser.cs
  Assets/Scripts/ObjectDisplayController.cs
  Assets/Scripts/OgreeClasses/Group.cs
  Assets/Scripts/OgreeClasses/Object.cs
  Assets/Scripts/OgreeGenerators/ObjectGenerator.cs
Labels: bug, enhancement

#401 Fixed label dupplicata
  Assets/Scripts/DisplayObjectData.cs
Labels: bug

#403 Fix fbxModel position
  Assets/Scripts/ModelLoader.cs
Labels: bug

#404 Fixed various U helpers bugs
  Assets/Scripts/ObjectDisplayController.cs
  Assets/Scripts/OgreeClasses/Rack.cs
  Assets/Scripts/UHelpersManager.cs
Labels: bug

#407 391 racks with sensors in their templates dont have a mean sensor in their upper front left corner
  Assets/Scripts/ObjectDisplayController.cs
  Assets/Scripts/ReadFromJson.cs
Labels: bug
