Repository ditrit/OGrEE-3D, pull requests merged in 2023-07, with the labels that each got.

#343 Fix racks pos and crashes
  Assets/Scenes/Main.unity
  Assets/Scripts/Inputs.cs
  Assets/Scripts/ModelLoader.cs
  Assets/Scripts/ObjectDisplayController.cs
  Assets/Scripts/OgreeGenerators/ObjectGenerator.cs
Labels: bug

#348 Fix bar chart and scatter plot bugs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Inputs.cs
  Assets/Scripts/ObjectDisplayController.cs
  Assets/Scripts/TempDiagram.cs
Labels: bug

#353 285 move all hard coded values to a separate file
  .gitignore
  Assets/Materials/Heatmap.mat
  Assets/Resources/config.toml
  Assets/Scripts/ApiManager.cs
  Assets/Scripts/CameraControl.cs
  Assets/Scripts/ConfigLoader.cs
  Assets/Scripts/DebugText.cs
  Assets/Scripts/DisplayObjectData.cs
  Assets/Scripts/Enums_Strucs/Enums.cs
  Assets/Scripts/Enums_Strucs/FixedValues.cs
  Assets/Scripts/Enums_Strucs/FixedValues.cs.meta
  Assets/Scripts/GUIObjectInfos.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/GridCell.cs
  Assets/Scripts/Inputs.cs
  Assets/Scripts/Network/CliParser.cs
  Assets/Scripts/ObjectDisplayController.cs
  Assets/Scripts/OgreeClasses/Object.cs
  Assets/Scripts/OgreeClasses/Room.cs
  Assets/Scripts/OgreeGenerators/NonSquareBuildingGenerator.cs
  Assets/Scripts/OgreeGenerators/ObjectGenerator.cs
  Assets/Scripts/OgreeGenerators/OgreeGenerator.cs
  Assets/Scripts/ReadFromJson.cs
  Assets/Scripts/TempDiagram.cs
  Assets/Scripts/UHelpersManager.cs
  Assets/Scripts/UiManager.cs
  Assets/Scripts/Utils.cs
Labels: bug, enhancement

#358 edit button is visible when rightclicking on nothing in edit mode
  Assets/Scripts/UiManager.cs
Labels: enhancement

#365 Fixed forced rack labels showing with bar chart
  Assets/Scripts/DisplayObjectData.cs
Labels: bug

#370 354 removing current selection while in get coords mode crashes the app
  Assets/Scripts/Inputs.cs
  Assets/Scripts/OgreeClasses/OgreeObject.cs
  Assets/Scripts/TempDiagram.cs
  Assets/Scripts/UiManager.cs
Labels: bug
