Repository ditrit/OGrEE-3D, pull requests merged in 2024-03, with the labels that each got.

#473 Toggle generic name
  Assets/Prefabs/Room.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/ModelLoader.cs
  Assets/Scripts/ObjectDisplayController.cs
  Assets/Scripts/OgreeClasses/Room.cs
  Assets/Scripts/UiManager.cs
Labels: bug, enhancement

#477 fix crashes related to attributes format
  Assets/Scripts/CameraControl.cs
  Assets/Scripts/ClearanceHandler.cs
  Assets/Scripts/OgreeClasses/Room.cs
Labels: bug

#480 479 label display errors
  Assets/Prefabs/LabeledBox.prefab
  Assets/Prefabs/Rack.prefab
  Assets/Scripts/DisplayObjectData.cs
  ProjectSettings/LocalizationSettings.asset
Labels: bug

#481 Modify pos from cli
  Assets/Scripts/Enums_Strucs/FixedValues.cs
  Assets/Scripts/Network/CommandParser.cs
  Assets/Scripts/OgreeClasses/Group.cs
  Assets/Scripts/OgreeClasses/Item.cs
  Assets/Scripts/OgreeGenerators/BuildingGenerator.cs
  Assets/Scripts/OgreeGenerators/ObjectGenerator.cs
  Assets/Scripts/Utils.cs
Labels: enhancement

#482 New locales (es + pt)
  Assets/AddressableAssetsData/AddressableAssetSettings.asset
  Assets/AddressableAssetsData/AssetGroups/Localization-Locales.asset
  Assets/AddressableAssetsData/AssetGroups/Localization-String-Tables-Portuguese (pt).asset
  Assets/AddressableAssetsData/AssetGroups/Localization-String-Tables-Portuguese (pt).asset.meta
  Assets/AddressableAssetsData/AssetGroups/Localization-String-Tables-Spanish (es).asset
  Assets/AddressableAssetsData/AssetGroups/Localization-String-Tables-Spanish (es).asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-String-Tables-Portuguese (pt)_BundledAssetGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-String-Tables-Portuguese (pt)_BundledAssetGroupSchema.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-String-Tables-Portuguese (pt)_ContentUpdateGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-String-Tables-Portuguese (pt)_ContentUpdateGroupSchema.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-String-Tables-Spanish (es)_BundledAssetGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-String-Tables-Spanish (es)_BundledAssetGroupSchema.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-String-Tables-Spanish (es)_ContentUpdateGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-String-Tables-Spanish (es)_ContentUpdateGroupSchema.asset.meta
  Assets/AddressableAssetsData/Windows/addressables_content_state.bin
  Assets/Localization/Portuguese (pt).asset
  Assets/Localization/Portuguese (pt).asset.meta
  Assets/Localization/Spanish (es).asset
  Assets/Localization/Spanish (es).asset.meta
  Assets/Localization/Texts.asset
  Assets/Localization/Texts_es.asset
  Assets/Localization/Texts_es.asset.meta
  Assets/Localization/Texts_pt.asset
  Assets/Localization/Texts_pt.asset.meta
  Assets/Prefabs/UI/PanelSettings.prefab
  ProjectSettings/ProjectSettings.asset
Labels: enhancement
